/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS TUF GAMING A15
 */
public class PenentuanJurusanSMK_GUI extends javax.swing.JFrame {

    /**
     * Creates new form PenentuanJurusanSMK_GUI
     */
    public PenentuanJurusanSMK_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_input = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        et_nama_siswa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        et_nilai_mat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        et_nilai_bahasa_indonesia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        et_nilai_bahasa_inggris = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        et_nilai_tik = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmb_kesehatan_mata = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        et_tinggi_badan = new javax.swing.JTextField();
        btn_lihat_hasil = new javax.swing.JButton();
        btn_reset_form = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_keputusan = new javax.swing.JLabel();
        txt_kalimat2 = new javax.swing.JLabel();
        txt_kalimat1 = new javax.swing.JLabel();
        txt_score_penilaian = new javax.swing.JLabel();
        txt_tkr = new javax.swing.JLabel();
        txt_tkj = new javax.swing.JLabel();
        txt_tgb = new javax.swing.JLabel();
        txt_tav = new javax.swing.JLabel();
        score_tkr = new javax.swing.JLabel();
        score_tkj = new javax.swing.JLabel();
        score_tgb = new javax.swing.JLabel();
        score_tav = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cmb_minat_tkr = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmb_minat_tkj = new javax.swing.JComboBox<>();
        cmb_minat_tgb = new javax.swing.JComboBox<>();
        cmb_minat_tav = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(49, 57, 76));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(81, 96, 127));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HOME");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel3.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, -1));

        btn_input.setBackground(new java.awt.Color(65, 76, 102));
        btn_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_inputMouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("INPUT DATA");

        javax.swing.GroupLayout btn_inputLayout = new javax.swing.GroupLayout(btn_input);
        btn_input.setLayout(btn_inputLayout);
        btn_inputLayout.setHorizontalGroup(
            btn_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        btn_inputLayout.setVerticalGroup(
            btn_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel3.add(btn_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, -1));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS TUF GAMING A15\\Downloads\\smk.png")); // NOI18N
        jPanel3.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(113, 134, 178));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM PENDUKUNG KEPUTUSAN");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENENTUAN JURUSAN SMK N 1 ADIWERNA (TOPSIS)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 1000, 130));

        et_nama_siswa.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        et_nama_siswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                et_nama_siswaKeyTyped(evt);
            }
        });
        bg.add(et_nama_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 460, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setText("NILAI MATEMATIKA");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        et_nilai_mat.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        et_nilai_mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_nilai_matActionPerformed(evt);
            }
        });
        et_nilai_mat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                et_nilai_matKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                et_nilai_matKeyTyped(evt);
            }
        });
        bg.add(et_nilai_mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 200, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setText("NILAI BAHASA INDONESIA");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        et_nilai_bahasa_indonesia.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        et_nilai_bahasa_indonesia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                et_nilai_bahasa_indonesiaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                et_nilai_bahasa_indonesiaKeyTyped(evt);
            }
        });
        bg.add(et_nilai_bahasa_indonesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 200, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setText("NILAI BAHASA INGGRIS");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        et_nilai_bahasa_inggris.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        et_nilai_bahasa_inggris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                et_nilai_bahasa_inggrisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                et_nilai_bahasa_inggrisKeyTyped(evt);
            }
        });
        bg.add(et_nilai_bahasa_inggris, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 200, -1));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setText("NILAI TIK");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        et_nilai_tik.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        et_nilai_tik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                et_nilai_tikKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                et_nilai_tikKeyTyped(evt);
            }
        });
        bg.add(et_nilai_tik, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 200, -1));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setText("KESEHATAN MATA");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        cmb_kesehatan_mata.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cmb_kesehatan_mata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "SEHAT", "MINUS 1", "MINUS > 1", "MINUS ≥ 3", "BUTA WARNA" }));
        cmb_kesehatan_mata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kesehatan_mataActionPerformed(evt);
            }
        });
        bg.add(cmb_kesehatan_mata, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 200, -1));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setText("TINGGI BADAN");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, -1, -1));

        et_tinggi_badan.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        et_tinggi_badan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                et_tinggi_badanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                et_tinggi_badanKeyTyped(evt);
            }
        });
        bg.add(et_tinggi_badan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 200, -1));

        btn_lihat_hasil.setBackground(new java.awt.Color(49, 57, 76));
        btn_lihat_hasil.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btn_lihat_hasil.setForeground(new java.awt.Color(255, 255, 255));
        btn_lihat_hasil.setText("LIHAT HASIL");
        btn_lihat_hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lihat_hasilActionPerformed(evt);
            }
        });
        bg.add(btn_lihat_hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 270, 120, -1));

        btn_reset_form.setBackground(new java.awt.Color(255, 255, 255));
        btn_reset_form.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btn_reset_form.setText("RESET FORM");
        btn_reset_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset_formActionPerformed(evt);
            }
        });
        bg.add(btn_reset_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 120, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "HASIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 0, 14))); // NOI18N

        txt_keputusan.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        txt_keputusan.setText(" ");

        txt_kalimat2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txt_kalimat2.setText(" ");

        txt_kalimat1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txt_kalimat1.setText(" ");

        txt_score_penilaian.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txt_score_penilaian.setText(" ");

        txt_tkr.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txt_tkr.setText(" ");

        txt_tkj.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txt_tkj.setText(" ");

        txt_tgb.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txt_tgb.setText(" ");

        txt_tav.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txt_tav.setText(" ");

        score_tkr.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        score_tkr.setText(" ");

        score_tkj.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        score_tkj.setText(" ");

        score_tgb.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        score_tgb.setText(" ");

        score_tav.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        score_tav.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_keputusan)
                    .addComponent(txt_kalimat2)
                    .addComponent(txt_kalimat1)
                    .addComponent(txt_score_penilaian)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tkr)
                            .addComponent(txt_tkj)
                            .addComponent(txt_tgb)
                            .addComponent(txt_tav))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(score_tkr)
                            .addComponent(score_tkj)
                            .addComponent(score_tgb)
                            .addComponent(score_tav))))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_keputusan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kalimat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kalimat2)
                .addGap(18, 18, 18)
                .addComponent(txt_score_penilaian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_tkr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tkj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tgb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tav))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(score_tkr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(score_tkj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(score_tgb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(score_tav)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 470, 350));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setText("NAMA SISWA");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "MINAT SISWA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 0, 14))); // NOI18N

        cmb_minat_tkr.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cmb_minat_tkr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "SANGAT MINAT", "MINAT", "CUKUP MINAT", "KURANG MINAT", "TIDAK MINAT" }));
        cmb_minat_tkr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_minat_tkrActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel17.setText("TKR");

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel18.setText("TKJ");

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel19.setText("TGB");

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel20.setText("TAV");

        cmb_minat_tkj.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cmb_minat_tkj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "SANGAT MINAT", "MINAT", "CUKUP MINAT", "KURANG MINAT", "TIDAK MINAT" }));

        cmb_minat_tgb.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cmb_minat_tgb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "SANGAT MINAT", "MINAT", "CUKUP MINAT", "KURANG MINAT", "TIDAK MINAT" }));

        cmb_minat_tav.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cmb_minat_tav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "SANGAT MINAT", "MINAT", "CUKUP MINAT", "KURANG MINAT", "TIDAK MINAT" }));

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*Note : Pilihan minat antar");

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("  jurusan tidak boleh sama");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(cmb_minat_tkr, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_minat_tkj, javax.swing.GroupLayout.Alignment.LEADING, 0, 195, Short.MAX_VALUE)
                            .addComponent(cmb_minat_tgb, javax.swing.GroupLayout.Alignment.LEADING, 0, 195, Short.MAX_VALUE)
                            .addComponent(cmb_minat_tav, javax.swing.GroupLayout.Alignment.LEADING, 0, 195, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_minat_tkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_minat_tkj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_minat_tgb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_minat_tav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        bg.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 310, 230, -1));

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lihat_hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihat_hasilActionPerformed
        perhitungan();
    }//GEN-LAST:event_btn_lihat_hasilActionPerformed

    private void cmb_kesehatan_mataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kesehatan_mataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kesehatan_mataActionPerformed

    private void et_nilai_matKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nilai_matKeyTyped
        validasi_angka(evt);
    }//GEN-LAST:event_et_nilai_matKeyTyped

    private void et_nilai_bahasa_indonesiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nilai_bahasa_indonesiaKeyTyped
        validasi_angka(evt);
    }//GEN-LAST:event_et_nilai_bahasa_indonesiaKeyTyped

    private void et_nilai_bahasa_inggrisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nilai_bahasa_inggrisKeyTyped
        validasi_angka(evt);
    }//GEN-LAST:event_et_nilai_bahasa_inggrisKeyTyped

    private void et_nilai_tikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nilai_tikKeyTyped
        validasi_angka(evt);
    }//GEN-LAST:event_et_nilai_tikKeyTyped

    private void et_tinggi_badanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_tinggi_badanKeyTyped
        validasi_angka(evt);
    }//GEN-LAST:event_et_tinggi_badanKeyTyped

    private void et_nilai_matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_nilai_matActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_nilai_matActionPerformed

    private void et_nama_siswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nama_siswaKeyTyped
        validasi_huruf(evt);
    }//GEN-LAST:event_et_nama_siswaKeyTyped

    private void cmb_minat_tkrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_minat_tkrActionPerformed

    }//GEN-LAST:event_cmb_minat_tkrActionPerformed

    private void btn_reset_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset_formActionPerformed
        reset_form();
    }//GEN-LAST:event_btn_reset_formActionPerformed

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        btn_home.setBackground(new Color(65, 76, 102));
        btn_input.setBackground(new Color(81, 96, 127));
        this.setVisible(false);
        HOME home = new HOME();
        home.setVisible(true);
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inputMouseClicked
        btn_input.setBackground(new Color(65, 76, 102));
        btn_home.setBackground(new Color(81, 96, 127));
    }//GEN-LAST:event_btn_inputMouseClicked

    private void et_nilai_matKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nilai_matKeyReleased
        int a = Integer.parseInt(et_nilai_mat.getText());
        if (a >= 100) {
            JOptionPane.showMessageDialog(this, "Nilai tidak boleh diatas 100");
            et_nilai_mat.setText("");
        }
    }//GEN-LAST:event_et_nilai_matKeyReleased

    private void et_nilai_bahasa_indonesiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nilai_bahasa_indonesiaKeyReleased
        int b = Integer.parseInt(et_nilai_bahasa_indonesia.getText());
        if (b >= 100) {
            JOptionPane.showMessageDialog(this, "Nilai tidak boleh diatas 100");
            et_nilai_bahasa_indonesia.setText("");
        }
    }//GEN-LAST:event_et_nilai_bahasa_indonesiaKeyReleased

    private void et_nilai_bahasa_inggrisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nilai_bahasa_inggrisKeyReleased
        int c = Integer.parseInt(et_nilai_bahasa_inggris.getText());
        if (c >= 100) {
            JOptionPane.showMessageDialog(this, "Nilai tidak boleh diatas 100");
            et_nilai_bahasa_inggris.setText("");
        }
    }//GEN-LAST:event_et_nilai_bahasa_inggrisKeyReleased

    private void et_nilai_tikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_nilai_tikKeyReleased
        int d = Integer.parseInt(et_nilai_tik.getText());
        if (d >= 100) {
            JOptionPane.showMessageDialog(this, "Nilai tidak boleh diatas 100");
            et_nilai_tik.setText("");
        }
    }//GEN-LAST:event_et_nilai_tikKeyReleased

    private void et_tinggi_badanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_tinggi_badanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_et_tinggi_badanKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenentuanJurusanSMK_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenentuanJurusanSMK_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenentuanJurusanSMK_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenentuanJurusanSMK_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenentuanJurusanSMK_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_input;
    private javax.swing.JButton btn_lihat_hasil;
    private javax.swing.JButton btn_reset_form;
    private javax.swing.JComboBox<String> cmb_kesehatan_mata;
    private javax.swing.JComboBox<String> cmb_minat_tav;
    private javax.swing.JComboBox<String> cmb_minat_tgb;
    private javax.swing.JComboBox<String> cmb_minat_tkj;
    private javax.swing.JComboBox<String> cmb_minat_tkr;
    private javax.swing.JTextField et_nama_siswa;
    private javax.swing.JTextField et_nilai_bahasa_indonesia;
    private javax.swing.JTextField et_nilai_bahasa_inggris;
    private javax.swing.JTextField et_nilai_mat;
    private javax.swing.JTextField et_nilai_tik;
    private javax.swing.JTextField et_tinggi_badan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel score_tav;
    private javax.swing.JLabel score_tgb;
    private javax.swing.JLabel score_tkj;
    private javax.swing.JLabel score_tkr;
    private javax.swing.JLabel txt_kalimat1;
    private javax.swing.JLabel txt_kalimat2;
    private javax.swing.JLabel txt_keputusan;
    private javax.swing.JLabel txt_score_penilaian;
    private javax.swing.JLabel txt_tav;
    private javax.swing.JLabel txt_tgb;
    private javax.swing.JLabel txt_tkj;
    private javax.swing.JLabel txt_tkr;
    // End of variables declaration//GEN-END:variables

    public void validasi_huruf(KeyEvent a) {
        if (Character.isDigit(a.getKeyChar())) {
            a.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Huruf", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void validasi_angka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())) {
            b.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void perhitungan() {
        if (et_nama_siswa.getText().equals("") && et_nilai_mat.getText().equals("")
                && et_nilai_bahasa_indonesia.getText().equals("") && et_nilai_bahasa_inggris.getText().equals("")
                && et_nilai_tik.getText().equals("") && et_tinggi_badan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Tidak Boleh Kosong!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (cmb_kesehatan_mata.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih Kesehatan Mata", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (cmb_minat_tkr.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih Minat TKR", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (cmb_minat_tkj.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih Minat TKJ", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (cmb_minat_tav.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih Minat TAV", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (cmb_minat_tgb.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih Minat TGB", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
            int kepentingan_minat = 5;
            int kepentingan_mat = 4;
            int kepentingan_indo = 3;
            int kepentingan_inggris = 3;
            int kepentingan_tik = 4;
            int kepentingan_kes_mata = 5;
            int kepentingan_tb = 4;

//        **************************************** GET TEXT ****************************************
            String nama_siswa = et_nama_siswa.getText().toUpperCase();

            int nilai_mat = Integer.parseInt(et_nilai_mat.getText());
            int nilai_indo = Integer.parseInt(et_nilai_bahasa_indonesia.getText());
            int nilai_inggris = Integer.parseInt(et_nilai_bahasa_inggris.getText());
            int nilai_tik = Integer.parseInt(et_nilai_tik.getText());
            int tinggi_badan = Integer.parseInt(et_tinggi_badan.getText());

//        ************************************ DEKLARASI VARIABLE **********************************
            double mat_tkr, mat_tkj, mat_tgb, mat_tav;
            double indo_tkr, indo_tkj, indo_tgb, indo_tav;
            double inggris_tkr, inggris_tkj, inggris_tgb, inggris_tav;
            double tik_tkr, tik_tkj, tik_tgb, tik_tav;

//        ************************************* PEMBOBOTAN AWAL ************************************
//        ****************************************** MINAT *****************************************
            int cmb_tkr = cmb_minat_tkr.getSelectedIndex();
            int cmb_tkj = cmb_minat_tkj.getSelectedIndex();
            int cmb_tgb = cmb_minat_tgb.getSelectedIndex();
            int cmb_tav = cmb_minat_tav.getSelectedIndex();

            int minat_tkr, minat_tkj, minat_tgb, minat_tav;

//        *********************************** MINAT TKR ************************************
            switch (cmb_tkr) {
                case 1:
                    minat_tkr = 5;
                    break;
                case 2:
                    minat_tkr = 4;
                    break;
                case 3:
                    minat_tkr = 3;
                    break;
                case 4:
                    minat_tkr = 2;
                    break;
                case 5:
                    minat_tkr = 1;
                    break;
                default:
                    minat_tkr = 0;
                    break;
            }

//        *********************************** MINAT TKJ ************************************
            switch (cmb_tkj) {
                case 1:
                    minat_tkj = 5;
                    break;
                case 2:
                    minat_tkj = 4;
                    break;
                case 3:
                    minat_tkj = 3;
                    break;
                case 4:
                    minat_tkj = 2;
                    break;
                case 5:
                    minat_tkj = 1;
                    break;
                default:
                    minat_tkj = 0;
                    break;
            }
//        *********************************** MINAT TGB ************************************

            switch (cmb_tgb) {
                case 1:
                    minat_tgb = 5;
                    break;
                case 2:
                    minat_tgb = 4;
                    break;
                case 3:
                    minat_tgb = 3;
                    break;
                case 4:
                    minat_tgb = 2;
                    break;
                case 5:
                    minat_tgb = 1;
                    break;
                default:
                    minat_tgb = 0;
                    break;
            }
//        *********************************** MINAT TAV ************************************

            switch (cmb_tav) {
                case 1:
                    minat_tav = 5;
                    break;
                case 2:
                    minat_tav = 4;
                    break;
                case 3:
                    minat_tav = 3;
                    break;
                case 4:
                    minat_tav = 2;
                    break;
                case 5:
                    minat_tav = 1;
                    break;
                default:
                    minat_tav = 0;
                    break;
            }

//        ************************************* NILAI MATEMATIKA ***********************************
            if (nilai_mat >= 80 && nilai_mat <= 100) {
                mat_tkr = 0.75;
                mat_tkj = 0.75;
                mat_tgb = 1;
                mat_tav = 0.5;
            } else if (nilai_mat >= 70 && nilai_mat <= 79) {
                mat_tkr = 0.5;
                mat_tkj = 0.75;
                mat_tgb = 0.75;
                mat_tav = 0.25;
            } else if (nilai_mat >= 60 && nilai_mat <= 69) {
                mat_tkr = 0.25;
                mat_tkj = 0.5;
                mat_tgb = 0.5;
                mat_tav = 0.25;
            } else {
                mat_tkr = 0;
                mat_tkj = 0;
                mat_tgb = 0;
                mat_tav = 0;
            }

//        ********************************** NILAI BAHASA INDONESIA ***********************************
            if (nilai_indo >= 80 && nilai_indo <= 100) {
                indo_tkr = 0.75;
                indo_tkj = 0.75;
                indo_tgb = 1;
                indo_tav = 1;
            } else if (nilai_indo >= 70 && nilai_indo <= 79) {
                indo_tkr = 0.5;
                indo_tkj = 0.5;
                indo_tgb = 0.75;
                indo_tav = 0.75;
            } else if (nilai_indo >= 60 && nilai_indo <= 69) {
                indo_tkr = 0.25;
                indo_tkj = 0.25;
                indo_tgb = 0.5;
                indo_tav = 0.5;
            } else {
                indo_tkr = 0;
                indo_tkj = 0;
                indo_tgb = 0;
                indo_tav = 0;
            }

//        *********************************** NILAI BAHASA INGGRIS ************************************
            if (nilai_inggris >= 80 && nilai_inggris <= 100) {
                inggris_tkr = 0.75;
                inggris_tkj = 1;
                inggris_tgb = 1;
                inggris_tav = 0.25;
            } else if (nilai_inggris >= 70 && nilai_inggris <= 79) {
                inggris_tkr = 0.5;
                inggris_tkj = 0.75;
                inggris_tgb = 0.75;
                inggris_tav = 0.5;
            } else if (nilai_inggris >= 60 && nilai_inggris <= 69) {
                inggris_tkr = 0.25;
                inggris_tkj = 0.5;
                inggris_tgb = 0.5;
                inggris_tav = 0.25;
            } else {
                inggris_tkr = 0;
                inggris_tkj = 0;
                inggris_tgb = 0;
                inggris_tav = 0;
            }
//        ***************************************** NILAI TIK ******************************************
            if (nilai_tik >= 80 && nilai_tik <= 100) {
                tik_tkr = 0.75;
                tik_tkj = 1;
                tik_tgb = 1;
                tik_tav = 0.25;
            } else if (nilai_tik >= 70 && nilai_tik <= 79) {
                tik_tkr = 0.5;
                tik_tkj = 0.75;
                tik_tgb = 0.75;
                tik_tav = 0.5;
            } else if (nilai_tik >= 60 && nilai_tik <= 69) {
                tik_tkr = 0.25;
                tik_tkj = 0.5;
                tik_tgb = 0.5;
                tik_tav = 0.25;
            } else {
                tik_tkr = 0;
                tik_tkj = 0;
                tik_tgb = 0;
                tik_tav = 0;
            }

//        *********************************** KESEHATAN MATA ************************************
            int cmb_kes_mata = cmb_kesehatan_mata.getSelectedIndex();
            int kes_mata;
            switch (cmb_kes_mata) {
                case 1:
                    kes_mata = 5;
                    break;
                case 2:
                    kes_mata = 4;
                    break;
                case 3:
                    kes_mata = 3;
                    break;
                case 4:
                    kes_mata = 2;
                    break;
                case 5:
                    kes_mata = 1;
                    break;
                default:
                    kes_mata = 0;
                    break;
            }

//        ***************************************** TINGGI BADAN ******************************************
            int tb;
            if (tinggi_badan >= 170) {
                tb = 5;
            } else if (tinggi_badan >= 160 && tinggi_badan <= 169) {
                tb = 4;
            } else if (tinggi_badan >= 155 && tinggi_badan <= 159) {
                tb = 3;
            } else if (tinggi_badan >= 150 && tinggi_badan <= 154) {
                tb = 2;
            } else if (tinggi_badan >= 145 && tinggi_badan <= 149) {
                tb = 1;
            } else {
                tb = 0;
            }

//        *********************************** MENENTUKAN NILAI PEMBAGI ************************************
            double pembagi_minat = Math.sqrt(Math.pow(minat_tkr, 2) + Math.pow(minat_tkj, 2) + Math.pow(minat_tgb, 2) + Math.pow(minat_tav, 2));
            double pembagi_mat = Math.sqrt(Math.pow(mat_tkr, 2) + Math.pow(mat_tkj, 2) + Math.pow(mat_tgb, 2) + Math.pow(mat_tav, 2));
            double pembagi_indo = Math.sqrt(Math.pow(indo_tkr, 2) + Math.pow(indo_tkj, 2) + Math.pow(indo_tgb, 2) + Math.pow(indo_tav, 2));
            double pembagi_inggris = Math.sqrt(Math.pow(inggris_tkr, 2) + Math.pow(inggris_tkj, 2) + Math.pow(inggris_tgb, 2) + Math.pow(inggris_tav, 2));
            double pembagi_tik = Math.sqrt(Math.pow(tik_tkr, 2) + Math.pow(tik_tkj, 2) + Math.pow(tik_tgb, 2) + Math.pow(tik_tav, 2));
            double pembagi_kes_mata = Math.sqrt(Math.pow(kes_mata, 2) + Math.pow(kes_mata, 2) + Math.pow(kes_mata, 2) + Math.pow(kes_mata, 2));
            double pembagi_tb = Math.sqrt(Math.pow(tb, 2) + Math.pow(tb, 2) + Math.pow(tb, 2) + Math.pow(tb, 2));

//*************************************************************************************************************************************** MENGHITUNG TERNORMALISASI 
//        *********************************** TERNORMALISASI MINAT ************************************
            double t_minat_tkr = minat_tkr / pembagi_minat;
            double t_minat_tkj = minat_tkj / pembagi_minat;
            double t_minat_tgb = minat_tgb / pembagi_minat;
            double t_minat_tav = minat_tav / pembagi_minat;
//        *********************************** TERNORMALISASI NILAI MAT ************************************
            double t_mat_tkr = mat_tkr / pembagi_mat;
            double t_mat_tkj = mat_tkj / pembagi_mat;
            double t_mat_tgb = mat_tgb / pembagi_mat;
            double t_mat_tav = mat_tav / pembagi_mat;
//        *********************************** TERNORMALISASI NILAI BAHASA INDONESIA ************************************
            double t_indo_tkr = indo_tkr / pembagi_indo;
            double t_indo_tkj = indo_tkj / pembagi_indo;
            double t_indo_tgb = indo_tgb / pembagi_indo;
            double t_indo_tav = indo_tav / pembagi_indo;
//        *********************************** TERNORMALISASI NILAI BAHASA INGGRIS ************************************
            double t_inggris_tkr = inggris_tkr / pembagi_inggris;
            double t_inggris_tkj = inggris_tkj / pembagi_inggris;
            double t_inggris_tgb = inggris_tgb / pembagi_inggris;
            double t_inggris_tav = inggris_tav / pembagi_inggris;
//        *********************************** TERNORMALISASI NILAI TIK ************************************
            double t_tik_tkr = tik_tkr / pembagi_tik;
            double t_tik_tkj = tik_tkj / pembagi_tik;
            double t_tik_tgb = tik_tgb / pembagi_tik;
            double t_tik_tav = tik_tav / pembagi_tik;
//        *********************************** TERNORMALISASI KESEHATAN MATA ************************************
            double t_kes_mata_tkr = kes_mata / pembagi_kes_mata;
            double t_kes_mata_tkj = kes_mata / pembagi_kes_mata;
            double t_kes_mata_tgb = kes_mata / pembagi_kes_mata;
            double t_kes_mata_tav = kes_mata / pembagi_kes_mata;
//        *********************************** TERNORMALISASI TINGGI BADAN ************************************
            double t_tb_tkr = tb / pembagi_tb;
            double t_tb_tkj = tb / pembagi_tb;
            double t_tb_tgb = tb / pembagi_tb;
            double t_tb_tav = tb / pembagi_tb;

//*************************************************************************************************************************************** MENGHITUNG TERNORMALISASI TERBOBOT
//        *********************************** TERNORMALISASI TERBOBOT MINAT ************************************
            double terbobot_minat_tkr = kepentingan_minat * t_minat_tkr;
            double terbobot_minat_tkj = kepentingan_minat * t_minat_tkj;
            double terbobot_minat_tgb = kepentingan_minat * t_minat_tgb;
            double terbobot_minat_tav = kepentingan_minat * t_minat_tav;
//        *********************************** TERNORMALISASI TERBOBOT NIALAI MATEMATIKA ************************************
            double terbobot_mat_tkr = kepentingan_mat * t_mat_tkr;
            double terbobot_mat_tkj = kepentingan_mat * t_mat_tkj;
            double terbobot_mat_tgb = kepentingan_mat * t_mat_tgb;
            double terbobot_mat_tav = kepentingan_mat * t_mat_tav;
//        *********************************** TERNORMALISASI TERBOBOT NILAI BAHASA INDONESIA ************************************
            double terbobot_indo_tkr = kepentingan_indo * t_indo_tkr;
            double terbobot_indo_tkj = kepentingan_indo * t_indo_tkj;
            double terbobot_indo_tgb = kepentingan_indo * t_indo_tgb;
            double terbobot_indo_tav = kepentingan_indo * t_indo_tav;
//        *********************************** TERNORMALISASI TERBOBOT NILAI BAHASA INGGRIS************************************
            double terbobot_inggris_tkr = kepentingan_inggris * t_inggris_tkr;
            double terbobot_inggris_tkj = kepentingan_inggris * t_inggris_tkj;
            double terbobot_inggris_tgb = kepentingan_inggris * t_inggris_tgb;
            double terbobot_inggris_tav = kepentingan_inggris * t_inggris_tav;
//        *********************************** TERNORMALISASI TERBOBOT NILAI TIK ************************************
            double terbobot_tik_tkr = kepentingan_tik * t_tik_tkr;
            double terbobot_tik_tkj = kepentingan_tik * t_tik_tkj;
            double terbobot_tik_tgb = kepentingan_tik * t_tik_tgb;
            double terbobot_tik_tav = kepentingan_tik * t_tik_tav;
//        *********************************** TERNORMALISASI TERBOBOT KESEHATAN MATA ************************************
            double terbobot_kes_mata_tkr = kepentingan_kes_mata * t_kes_mata_tkr;
            double terbobot_kes_mata_tkj = kepentingan_kes_mata * t_kes_mata_tkj;
            double terbobot_kes_mata_tgb = kepentingan_kes_mata * t_kes_mata_tgb;
            double terbobot_kes_mata_tav = kepentingan_kes_mata * t_kes_mata_tav;
//        *********************************** TERNORMALISASI TERBOBOT TINGGI BADAN ************************************
            double terbobot_tb_tkr = kepentingan_tb * t_tb_tkr;
            double terbobot_tb_tkj = kepentingan_tb * t_tb_tkj;
            double terbobot_tb_tgb = kepentingan_tb * t_tb_tgb;
            double terbobot_tb_tav = kepentingan_tb * t_tb_tav;

//*************************************************************************************************************************************** MENCARI NILAI A+
//        *********************************** A+ MINAT ************************************
            List list_minat = new ArrayList();
            list_minat.add(terbobot_minat_tkr);
            list_minat.add(terbobot_minat_tkj);
            list_minat.add(terbobot_minat_tgb);
            list_minat.add(terbobot_minat_tav);
            double AplusMinat = (double) Collections.max(list_minat);
//        *********************************** A+ MAT ************************************ (BENEFIT)
            List list_mat = new ArrayList();
            list_mat.add(terbobot_mat_tkr);
            list_mat.add(terbobot_mat_tkj);
            list_mat.add(terbobot_mat_tgb);
            list_mat.add(terbobot_mat_tav);
            double AplusMat = (double) Collections.max(list_mat);
//        *********************************** A+ BAHASA INDONESIA ************************************ (BENEFIT)
            List list_indo = new ArrayList();
            list_indo.add(terbobot_indo_tkr);
            list_indo.add(terbobot_indo_tkj);
            list_indo.add(terbobot_indo_tgb);
            list_indo.add(terbobot_indo_tav);
            double AplusIndo = (double) Collections.max(list_indo);
//        *********************************** A+ BAHASA INGGRIS ************************************ (BENEFIT)
            List list_inggris = new ArrayList();
            list_inggris.add(terbobot_inggris_tkr);
            list_inggris.add(terbobot_inggris_tkj);
            list_inggris.add(terbobot_inggris_tgb);
            list_inggris.add(terbobot_inggris_tav);
            double AplusInggris = (double) Collections.max(list_inggris);
//        *********************************** A+ TIK ************************************ (BENEFIT)
            List list_tik = new ArrayList();
            list_tik.add(terbobot_tik_tkr);
            list_tik.add(terbobot_tik_tkj);
            list_tik.add(terbobot_tik_tgb);
            list_tik.add(terbobot_tik_tav);
            double AplusTik = (double) Collections.max(list_tik);
//        *********************************** A+ KESEHATAN MATA ************************************ (COST)
            List list_kes_mata = new ArrayList();
            list_kes_mata.add(terbobot_kes_mata_tkr);
            list_kes_mata.add(terbobot_kes_mata_tkj);
            list_kes_mata.add(terbobot_kes_mata_tgb);
            list_kes_mata.add(terbobot_kes_mata_tav);
            double AplusKesMata = (double) Collections.min(list_kes_mata);
//        *********************************** A+ TINGGI BADAN ************************************ (BENEFIT)
            List list_tb = new ArrayList();
            list_tb.add(terbobot_tb_tkr);
            list_tb.add(terbobot_tb_tkj);
            list_tb.add(terbobot_tb_tgb);
            list_tb.add(terbobot_tb_tav);
            double AplusTb = (double) Collections.max(list_tb);

//*************************************************************************************************************************************** MENCARI NILAI A-
//        *********************************** A- MINAT ************************************
            List list_minat2 = new ArrayList();
            list_minat2.add(terbobot_minat_tkr);
            list_minat2.add(terbobot_minat_tkj);
            list_minat2.add(terbobot_minat_tgb);
            list_minat2.add(terbobot_minat_tav);
            double AminMinat = (double) Collections.min(list_minat2);
//        *********************************** A- MAT ************************************ (BENEFIT)
            List list_mat2 = new ArrayList();
            list_mat2.add(terbobot_mat_tkr);
            list_mat2.add(terbobot_mat_tkj);
            list_mat2.add(terbobot_mat_tgb);
            list_mat2.add(terbobot_mat_tav);
            double AminMat = (double) Collections.min(list_mat2);
//        *********************************** A- BAHASA INDONESIA ************************************ (BENEFIT)
            List list_indo2 = new ArrayList();
            list_indo2.add(terbobot_indo_tkr);
            list_indo2.add(terbobot_indo_tkj);
            list_indo2.add(terbobot_indo_tgb);
            list_indo2.add(terbobot_indo_tav);
            double AminIndo = (double) Collections.min(list_indo2);
//        *********************************** A- BAHASA INGGRIS ************************************ (BENEFIT)
            List list_inggris2 = new ArrayList();
            list_inggris2.add(terbobot_inggris_tkr);
            list_inggris2.add(terbobot_inggris_tkj);
            list_inggris2.add(terbobot_inggris_tgb);
            list_inggris2.add(terbobot_inggris_tav);
            double AminInggris = (double) Collections.min(list_inggris2);
//        *********************************** A- TIK ************************************ (BENEFIT)
            List list_tik2 = new ArrayList();
            list_tik2.add(terbobot_tik_tkr);
            list_tik2.add(terbobot_tik_tkj);
            list_tik2.add(terbobot_tik_tgb);
            list_tik2.add(terbobot_tik_tav);
            double AminTik = (double) Collections.min(list_tik2);
//        *********************************** A+ KESEHATAN MATA ************************************ (COST)
            List list_kes_mata2 = new ArrayList();
            list_kes_mata2.add(terbobot_kes_mata_tkr);
            list_kes_mata2.add(terbobot_kes_mata_tkj);
            list_kes_mata2.add(terbobot_kes_mata_tgb);
            list_kes_mata2.add(terbobot_kes_mata_tav);
            double AminKesMata = (double) Collections.max(list_kes_mata2);
//        *********************************** A+ TINGGI BADAN ************************************ (BENEFIT)
            List list_tb2 = new ArrayList();
            list_tb2.add(terbobot_tb_tkr);
            list_tb2.add(terbobot_tb_tkj);
            list_tb2.add(terbobot_tb_tgb);
            list_tb2.add(terbobot_tb_tav);
            double AminTb = (double) Collections.min(list_tb2);

//****************************************************************************************************************************** D+        
//        *********************************** D+ TKR ************************************
            double DplusTKR = Math.sqrt(Math.pow((AplusMinat - terbobot_minat_tkr), 2)
                    + Math.pow((AplusMat - terbobot_mat_tkr), 2)
                    + Math.pow((AplusIndo - terbobot_indo_tkr), 2)
                    + Math.pow((AplusInggris - terbobot_inggris_tkr), 2)
                    + Math.pow((AplusTik - terbobot_tik_tkr), 2)
                    + Math.pow((AplusKesMata - terbobot_kes_mata_tkr), 2)
                    + Math.pow((AplusTb - terbobot_tb_tkr), 2));

//        *********************************** D+ TKJ ************************************
            double DplusTKJ = Math.sqrt(Math.pow((AplusMinat - terbobot_minat_tkj), 2)
                    + Math.pow((AplusMat - terbobot_mat_tkj), 2)
                    + Math.pow((AplusIndo - terbobot_indo_tkj), 2)
                    + Math.pow((AplusInggris - terbobot_inggris_tkj), 2)
                    + Math.pow((AplusTik - terbobot_tik_tkj), 2)
                    + Math.pow((AplusKesMata - terbobot_kes_mata_tkj), 2)
                    + Math.pow((AplusTb - terbobot_tb_tkj), 2));

//        *********************************** D+ TGB ************************************
            double DplusTGB = Math.sqrt(Math.pow((AplusMinat - terbobot_minat_tgb), 2)
                    + Math.pow((AplusMat - terbobot_mat_tgb), 2)
                    + Math.pow((AplusIndo - terbobot_indo_tgb), 2)
                    + Math.pow((AplusInggris - terbobot_inggris_tgb), 2)
                    + Math.pow((AplusTik - terbobot_tik_tgb), 2)
                    + Math.pow((AplusKesMata - terbobot_kes_mata_tgb), 2)
                    + Math.pow((AplusTb - terbobot_tb_tgb), 2));

//        *********************************** D+ TAV ************************************
            double DplusTAV = Math.sqrt(Math.pow((AplusMinat - terbobot_minat_tav), 2)
                    + Math.pow((AplusMat - terbobot_mat_tav), 2)
                    + Math.pow((AplusIndo - terbobot_indo_tav), 2)
                    + Math.pow((AplusInggris - terbobot_inggris_tav), 2)
                    + Math.pow((AplusTik - terbobot_tik_tav), 2)
                    + Math.pow((AplusKesMata - terbobot_kes_mata_tav), 2)
                    + Math.pow((AplusTb - terbobot_tb_tav), 2));

//*************************************************************************************************************************** D-        
//        *********************************** D- TKR ************************************
            double DminTKR = Math.sqrt(Math.pow((terbobot_minat_tkr - AminMinat), 2)
                    + Math.pow((terbobot_mat_tkr - AminMat), 2)
                    + Math.pow((terbobot_indo_tkr - AminIndo), 2)
                    + Math.pow((terbobot_inggris_tkr - AminInggris), 2)
                    + Math.pow((terbobot_tik_tkr - AminTik), 2)
                    + Math.pow((terbobot_kes_mata_tkr - AminKesMata), 2)
                    + Math.pow((terbobot_tb_tkr - AminTb), 2));
//        *********************************** D- TKJ ************************************
            double DminTKJ = Math.sqrt(Math.pow((terbobot_minat_tkj - AminMinat), 2)
                    + Math.pow((terbobot_mat_tkj - AminMat), 2)
                    + Math.pow((terbobot_indo_tkj - AminIndo), 2)
                    + Math.pow((terbobot_inggris_tkj - AminInggris), 2)
                    + Math.pow((terbobot_tik_tkj - AminTik), 2)
                    + Math.pow((terbobot_kes_mata_tkj - AminKesMata), 2)
                    + Math.pow((terbobot_tb_tkj - AminTb), 2));
//        *********************************** D- TGB ************************************
            double DminTGB = Math.sqrt(Math.pow((terbobot_minat_tgb - AminMinat), 2)
                    + Math.pow((terbobot_mat_tgb - AminMat), 2)
                    + Math.pow((terbobot_indo_tgb - AminIndo), 2)
                    + Math.pow((terbobot_inggris_tgb - AminInggris), 2)
                    + Math.pow((terbobot_tik_tgb - AminTik), 2)
                    + Math.pow((terbobot_kes_mata_tgb - AminKesMata), 2)
                    + Math.pow((terbobot_tb_tgb - AminTb), 2));
//        *********************************** D- TAV ************************************
            double DminTAV = Math.sqrt(Math.pow((terbobot_minat_tav - AminMinat), 2)
                    + Math.pow((terbobot_mat_tav - AminMat), 2)
                    + Math.pow((terbobot_indo_tav - AminIndo), 2)
                    + Math.pow((terbobot_inggris_tav - AminInggris), 2)
                    + Math.pow((terbobot_tik_tav - AminTik), 2)
                    + Math.pow((terbobot_kes_mata_tav - AminKesMata), 2)
                    + Math.pow((terbobot_tb_tav - AminTb), 2));

//*************************************************************************************************************************** V
            double v1 = DminTKR / (DminTKR + DplusTKR);
            double v2 = DminTKJ / (DminTKJ + DplusTKJ);
            double v3 = DminTGB / (DminTGB + DplusTGB);
            double v4 = DminTAV / (DminTAV + DplusTAV);

            String stringscoretkr = String.valueOf(v1);
            String stringscoretkj = String.valueOf(v2);
            String stringscoretav = String.valueOf(v3);
            String stringscoretgb = String.valueOf(v4);
            txt_score_penilaian.setText("SCORE PENILAIAN");
            txt_tkr.setText("TKR");
            txt_tkj.setText("TKJ");
            txt_tav.setText("TAV");
            txt_tgb.setText("TGB");
            score_tkr.setText(stringscoretkr);
            score_tkj.setText(stringscoretkj);
            score_tav.setText(stringscoretav);
            score_tgb.setText(stringscoretgb);

            List V = new ArrayList();
            V.add(v1);
            V.add(v2);
            V.add(v3);
            V.add(v4);
            double nilai_v = (double) Collections.max(V);

            if (nilai_v == v1) {
                txt_keputusan.setForeground(Color.GREEN);
                txt_keputusan.setText("SELAMAT!!!");
                txt_kalimat1.setText("Pendaftar atas nama " + nama_siswa);
                txt_kalimat2.setText("diterima di jurusan TKR");
            } else if (nilai_v == v2) {
                txt_keputusan.setForeground(Color.GREEN);
                txt_keputusan.setText("SELAMAT!!!");
                txt_kalimat1.setText("Pendaftar atas nama " + nama_siswa);
                txt_kalimat2.setText("diterima di jurusan TKJ");
            } else if (nilai_v == v3) {
                txt_keputusan.setForeground(Color.GREEN);
                txt_keputusan.setText("SELAMAT!!!");
                txt_kalimat1.setText("Pendaftar atas nama " + nama_siswa);
                txt_kalimat2.setText("diterima di jurusan TGB");
            } else if (nilai_v == v4) {
                txt_keputusan.setForeground(Color.GREEN);
                txt_keputusan.setText("SELAMAT!!!");
                txt_kalimat1.setText("Pendaftar atas nama " + nama_siswa);
                txt_kalimat2.setText("diterima di jurusan TAV");
            } else {
                txt_keputusan.setForeground(Color.RED);
                txt_keputusan.setText("MOHON MAAF :(");
                txt_kalimat1.setText("Pendaftar atas nama " + nama_siswa + " dinyatakan gagal");
            }

        }

    

    private void reset_form() {
        et_nama_siswa.setText("");
        et_nilai_mat.setText("");
        et_nilai_bahasa_indonesia.setText("");
        et_nilai_bahasa_inggris.setText("");
        et_nilai_tik.setText("");
        cmb_kesehatan_mata.setSelectedIndex(0);
        et_tinggi_badan.setText("");
        cmb_minat_tkr.setSelectedIndex(0);
        cmb_minat_tkj.setSelectedIndex(0);
        cmb_minat_tgb.setSelectedIndex(0);
        cmb_minat_tav.setSelectedIndex(0);
        txt_keputusan.setText("");
        txt_kalimat1.setText("");
        txt_kalimat2.setText("");

    }

}
